[package]
name = "enum-supervisor-domains"
version = "0.1.0"
edition = "2024"

[dependencies]
heapless = "0.8.0"
panic-halt = "1.0.0"
riscv = "0.13.0"
riscv-rt = { version = "0.14", features=["s-mode", "single-hart"] }
spin = { version = "0.10.0", features = ["spin_mutex"] }
