# This is taken from: https://pre-commit.ci/lite.html
# The actions applies configuration from pre-commit using
# .pre-commit-config.yml to ensure code-style, quality ecc
name: Pre-commit CI

on:
  pull_request:
  push:
    branches: main

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: 3.x
    - uses: pre-commit/action@v3.0.1
    - uses: pre-commit-ci/lite-action@v1.1.0
      if: always()
